# Generated by Django 5.1.3 on 2025-01-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
