# Generated by Django 5.1.3 on 2025-01-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_borrow_approval_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
