# Generated by Django 5.1.3 on 2025-01-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_borrow_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='borrow',
            name='return_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='return_request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned'), ('Return Requested', 'Return Requested')], default='Pending', max_length=20),
        ),
    ]
