# Generated by Django 5.1.3 on 2025-01-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_remove_borrow_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='extension_requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='extension_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='borrow',
            name='new_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
